@baseUrl = http://localhost:3001
@token = {{authenticate_user.response.body.token}}
@refreshedToken = {{refresh_token.response.body.token}}

# @name create_user
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "email": "anderkaiti@gmail.com",
  "username": "andersonkaiti",
  "password": "123456"
}

###

# @name authenticate_user
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "anderkaiti@gmail.com",
  "password": "123456"
}

###

# @name refresh_token
POST {{baseUrl}}/api/auth/refresh
Content-Type: application/json
Authorization: Bearer {{token}}



###

# @name create_task
POST {{baseUrl}}/api/tasks
Content-Type: application/json
Authorization: Bearer {{refreshedToken}}


{
  "title": "Simple title",
  "description": "Simple description",
  "dueDate": "2024-06-13T10:00:00.000Z",
  "priority": "LOW",
  "status": "TODO",
  "userIds": ["39fec937-57c1-4309-9f0f-242f6d647b38", "de71f3d4-4e12-4bef-8bc1-7004ca31089a"]
}

###

# @name find_tasks
GET {{baseUrl}}/api/tasks?page=1&size=1
Authorization: Bearer {{refreshedToken}}

###

# @name delete_task
DELETE {{baseUrl}}/api/tasks/85e0cdfa-900e-499b-8891-2ba5bbc8fb9b
Authorization: Bearer {{refreshedToken}}

###

# @name get_task
GET {{baseUrl}}/api/tasks/85e0cdfa-900e-499b-8891-2ba5bbc8fb9b
Authorization: Bearer {{refreshedToken}}

###

# @name update_task
PUT {{baseUrl}}/api/tasks/98307037-9e38-42c4-80cc-7cb8811f4bb1
Content-Type: application/json
Authorization: Bearer {{refreshedToken}}

{
  "title": "Simple title 22",
  "description": "Simple description 22",
  "dueDate": "2024-06-13T10:00:00.000Z",
  "priority": "LOW",
  "status": "TODO",
  "createdAt": "2025-10-16T19:24:59.077Z",
  "updatedAt": "2025-10-16T19:24:59.077Z",
  "userIds": ["de71f3d4-4e12-4bef-8bc1-7004ca31089a"]
}

###

# @name create_comment
POST {{baseUrl}}/api/tasks/80d2e996-9f1f-4911-a1ed-3249ffbb0af8/comments
Content-Type: application/json
Authorization: Bearer {{refreshedToken}}

{
  "text": "One simple comment for testing",
  "userId": "f6114fa8-3ada-49dc-a625-778eb780e6a3"
}

###

# @name list_comments
GET {{baseUrl}}/api/tasks/01a39b93-e983-4b05-85be-6f89d9950efb/comments?page=1&size=4
Authorization: Bearer {{refreshedToken}}

###

# @name find_users
GET {{baseUrl}}/api/auth/users
Authorization: Bearer {{refreshedToken}}